name: PR

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  checks:
    uses: palasthotel/github-workflows/.github/workflows/wp-plugin-pr.yml@v1
    with:
      slug: postqueue-feeds
      dev-plugin-name: Postqueue Feeds (DEV)
      required-files: |
        public-functions.php
        inc/feed.php
        inc/rewrite.php
        inc/postqueue-screen.php
        template/postqueue-feed-rss2.php
        languages/postqueue-feeds.pot
        languages/postqueue-feeds-de_DE.mo
